[workspace]
resolver = "2"
members = [
  "crates/marmotter-transport",
  "crates/marmotter-shell",
  "apps/desktop/src-tauri",
  "apps/android/src-tauri",
]

[workspace.package]
version = "1.0.5"
edition = "2021"
license = "MIT"
repository = "https://github.com/d4shkova/marmotter"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
